server:
  port: ${PORT:8762}

## Classic Eureka configuration
eureka:
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:eureka-production-637b.up.railway.app}
    #hostname: ${HOSTNAME:172.17.0.2}
    #hostname: ${HOSTNAME:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:https://eureka-production-637b.up.railway.app/eureka}  #railway
      #defaultZone: ${EUREKA_URL:http://172.17.0.2:8761/eureka}                        #docker
      #defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}                        #docker

## Enable service discovery (with Eureka)
## lower-case-service-id is mandatory, otherwise is retrieved in upper case from Eureka
spring:
  application:
    name: gateway-acl
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://relatos-papel-front-end.vercel.app" # Cambia esto según tu frontend
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

## We enable the Actuator API to be able to access <<host>>/actuator/gateway/routes
## We expose the routings that have been automatically detected (all)
## Depending on the ROUTE_TABLES_ENABLED environment variable (true by default)
management:
  endpoint:
    gateway:
      enabled: ${ROUTE_TABLES_ENABLED:true}
  endpoints:
    web:
      exposure:
        include:
          - '*'
